### ISSUE TITLE
Add more granularity to style names

### ISSUE THREAD

**Issue by fsmunoz** [Judo-Documentation-Project/judotree#3]
It will likely be necessary to add more granularity to "style" names. "Style" is currently used as an umbrella term, which works for an initial approach:

* Judo
* Wrestling
* Kitō-ryū

There are two limitations to this approach:

## Different names

Judo is currently listed as "Kodokan Judo", which is a debatable option. Actually, all of these could be used:

* Judo
* Kodokan Judo
* Nihon-den Kōdōkan Jūdō

Like person names, we should have an "aka" section, perhaps will "long name" or "formal name", or just a list of alternative names. Something like this:

```yaml
style:
  id: JDP-S-5
  name:	Karate
  native_name: 空手
  aka:
    - name: Karatedo
      native_name: 空手道
  birth:
    date: 19th century
    location: Okinawa
    country_code: JPN
  sources:
    - uri: https://en.wikipedia.org/wiki/Karate
```

## Substyles, factions, tendencies

We will want to capture the differences in this, sooner than later. Examples:

* Wrestling: Freestyle, Greco, Catch...
* Aikido: Yoshinkan, Shodokan, Iwama,...
* Karate: Shotokai, Wado-ryu, Goju,ryu...

etc, etc.

The simplest way would be to add a `substyle` entry to `style` entries. We can however imagine a future use of tracking the evolution of styles themselves, and for that, a similar approach as we currently use for persons could be used.

An example for Wado-ryu:

```yaml
style:
  id:
  name:	Wadō-ryū
  native_name: 和道流
  aka:
    - name: Shinshu Wadoryu Karate-Jujutsu
  birth:
    date: 1929
    location:
    country_code: JPN
  parent_styles:
    - id:
      name: Karate
    - id:
      name: Shindō Yōshin-ryū
  sources:
    - uri: https://en.wikipedia.org/wiki/Wad%C5%8D-ry%C5%AB
```

There would tempting to image the `id` in a way that denotes hierarchy: so, `JDP-S-5` for Karate, and `JDP-S-5-1` for Wado-ryu, etc. This would however require constant changes to IDs in order to reflect changes in the database.

### Database

- Add the necessary fields to the YAML format.

### Parser

- Capture those fields and add them to the CYJSON (and other export formats)

### Explorer

- Visualise the "substyle" name in the edge labels, either by default or as an option.
- In a future implementation of filtering, allow the selection of edges by substyle.
